### PR TITLE
Creating Data Model - Blog App Project

### PR DESCRIPTION
**Pull request by ouasamine**
## Preview 
In this first part of the project, I set up the project files for my RoR app and created migrations for the app's database structure.

## Workflow
- Created the RoR app and set the default database type to PostgreSQL
- Created the migration file for `users` table
- Created the migration files for `posts` table and its foreign keys
- Created the migration files for `comments` table and its foreign keys
- Created the migration files for `likes` table and its foreign keys

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @ouasamine, Kindly use the updated version  of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme

**Comment by ouasamine** [comment]
Oh sorry @prolajumokeoni I forgot to add the readme!

**Comment by prolajumokeoni** [comment]
Hi @ouasamine, please add the key features and future features section, this is a requirement to get a review

**Comment by ouasamine** [comment]
@prolajumokeoni Done

**Review by prolajumokeoni — APPROVED** [review]
Hi @ouasamine 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Kindly fix the link to your MIT license it is broken 👍🏿 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ouasamine** [comment]
Thanks @prolajumokeoni

**Pull request merged**
